#!/bin/sh
input=$1

samtools view  -bh -f 96 $input > ${input%.*}.p1.bam
samtools view  -b -f 144 $input > ${input%.*}.p3.bam
samtools merge -f ${input%.*}.p.bam ${input%.*}.p1.bam ${input%.*}.p3.bam
rm ${input%.*}.p1.bam ${input%.*}.p3.bam
samtools view -bh -f 80 $input > ${input%.*}.n2.bam
samtools view -b -f 160 $input > ${input%.*}.n4.bam
samtools merge -f ${input%.*}.n.bam ${input%.*}.n2.bam ${input%.*}.n4.bam
rm ${input%.*}.n2.bam ${input%.*}.n4.bam
